// app/types/user.ts

export type UserRole = 'admin' | 'domiciliataire' | 'client'
export type UserStatus = 'pending' | 'approved' | 'active' | 'rejected'

export interface User {
  id: number
  nom: string
  prenom?: string
  email: string
  telephone?: string
  role: UserRole
  status: UserStatus
  activation_date?: string | null
  approved_by?: number | null
  approved_at?: string | null
  rejection_reason?: string | null
  created_at?: string
  photo_url?: string | null
  initials?: string
  // True when the current password was generated by the system (new
  // account or an admin-triggered reset) and hasn't been changed yet.
  must_change_password?: boolean
}

export interface PendingUser extends User {
  status: 'pending'
}