<?php
//
// Invoices generated per contract payment. numero_facture is
// auto-generated by the Facture model in the format FAC-YYYY-###.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('factures', function (Blueprint $table) {
            $table->id();

            $table->foreignId('contrat_id')
                ->constrained('contrats')
                ->cascadeOnUpdate()
                ->restrictOnDelete();

            $table->foreignId('entreprise_id')
                ->constrained('entreprises')
                ->cascadeOnUpdate()
                ->restrictOnDelete();

            // Denormalised for fast tenant filtering without a join
            // through contrats on every invoice list query.
            $table->foreignId('domiciliataire_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->string('numero_facture', 20)->unique()->nullable();
            $table->date('date_facture')->nullable();
            $table->decimal('montant_total', 10, 2)->nullable();
            $table->enum('statut', ['pending', 'paid', 'cancelled'])->default('pending');
            $table->timestamp('archived_at')->nullable();
            $table->timestamps();

            $table->index('contrat_id');
            $table->index('entreprise_id');
            $table->index('statut');
            $table->index('date_facture');
            $table->index('archived_at');
            $table->index(['domiciliataire_id', 'created_at']);
            $table->index(['domiciliataire_id', 'archived_at']);
            $table->index(['domiciliataire_id', 'statut']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('factures');
    }
};
